---
name: Release Rust Crate

# yamllint disable-line rule:truthy
on:
    release:
        types: [published]

jobs:
    run-ci:
        uses: ./.github/workflows/ci.yml

    publish-rust-crate:
        name: Publish ogn-aprs-parser
        needs: [run-ci]
        if: startsWith(github.event.release.tag_name, 'ogn-aprs-parser@v')
        runs-on: ubuntu-latest
        environment:
            name: crates-io-release
        permissions:
            id-token: write  # Required for OIDC token exchange - trusted publishing on crates.io
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            - name: Setup Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
            - name: Authenticate crates.io
              uses: rust-lang/crates-io-auth-action@v1
              id: auth
            - name: Publish to Crates.io
              env:
                  CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
              run: cargo publish -p ogn-aprs-parser
